logging:
  level:
    net.zethmayr.benjamin.spring.zuulrerere: TRACE

server:
  port: 9000

rerere:
  enabled: true
  webShibboleth: web
  prefixes: static
  extensions: js,json,css

zuul:
  routes:
    foo-service:
      path: /foo/api/**
      serviceId: foo-service
    bar-service:
      path: /bar/api/**
      url: http://localhost:8810
    foo-web:
      path: /foo/**
      url: http://localhost:8901
    bar-web:
      path: /bar/**
      serviceId: bar-web
#    nothing:
#      path: /**
#      url: http://localhost:6666

hystrix:
  command:
    myusers-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

foo-service:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:8801,http://localhost:8802
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

bar-web:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: http://localhost:8921,http://localhost:8922
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100
